[package]
name = "app-launcher"
version = "0.1.0"
authors = ["Bram Hoendervangers <bram.hoendervangers@gmail.com>"]

[dependencies]
rust-ini = "0.9.11"
glib = "0.1.0"
gdk = "0.5.0"
itertools = "0.5.2"
gdk-sys = "0.3.1"

[dependencies.gtk]
version = "0.1.0"
features = ["v3_10"]